### PR TITLE
Added new design for Sleep Activity & Added Sleep facts

### PR DESCRIPTION
**Pull request by Spikeysanju**

### CODE REVIEW

**Comment by vmiklos** [comment]
Can you please reabase on top of master and resolve your conflicts?

Also, I'm not sure about these sleep facts. :-) Like, I don't want to get into this stupid discussion how much sleep you need. Some people claim it's 6 hours, some need 10 hours, some want to take this in 2 pieces. I would leave this part out before people start hating the app just because the facts added here is not what they believe. You know, "live and let live".

**Comment by vmiklos** [comment]
Hrm, the other problem is that the only purpose of the sleep activity is that you can edit entries and you broke that. Notice how all the android:onClick="editDateTime" attributes are gone. I guess the easiest is if I just pick the useful subset of this PR and then close it. :-)

**Comment by vmiklos** [comment]
Merged as d7ffddf78db88a4b4c64bca879f795725ebb748d, thanks for your work!

**Comment by Spikeysanju** [comment]
Hi Vmiklos, I hope you're doing good. I've recently redesigned the
Plees-tracker app with Minimalistic Look, Below I have attached the
Refreshed look.

I'm contributing to a repository for *Hacktoberfest*, Can you create a new
issue with a tag called *Hacktoberfest *?. So that I can send you the PR
for refreshed look & Code optimization.

Feel free to ping me if you have any questions.

Thanks & Regards,

Sanju S

**Comment by vmiklos** [comment]
I'm afraid you forgot to actually show the look. I don't mind to improve it further, but if you want an issue for your work, please create it yourself. Thanks.

**Pull request closed without merging**
