### PR TITLE
Fixed Layout Issues

### PR DESCRIPTION
**Pull request by Spikeysanju**

### CODE REVIEW

**Comment by vmiklos** [comment]
Can't merge this due to conflicts, but it seems you just forgot to rebase before authoring your 2nd PR. :-) I'll pick 99e698d to master and then just close this.

And yes, the fix works for me, thanks!

**Comment by vmiklos** [comment]
Merged as https://github.com/vmiklos/plees-tracker/commit/89ec20893ccb621703bca9237b00afa23f96619a

**Comment by vmiklos** [comment]
When you tap on a sleep item on the sleep list, the sleep activity opens, which is still the old design. Would it make sense to make it also use the same icons, etc?

**Comment by Spikeysanju** [comment]
I'm working on it. In second activity we will show data with different UI.

**Pull request closed without merging**
