### PR TITLE
Adds export to calendar functionality

### LINKED ISSUE #41: Possibility to synchronise tracks with calendar
The description is from here:

https://github.com/vmiklos/plees-tracker/issues/29

The tracks of sleep will be synchronised to given (by setting) calendar.

It will serve as both as visualisation and backup.

### PR DESCRIPTION
**Pull request by ed-george**
- Adds export to calendar functionality. Fixes #41

### CODE REVIEW

**Comment by vmiklos** [comment]
Thanks! Could you please rebase this branch against latest master?

**Comment by vmiklos** [comment]
Do you need help with the rebasing? Something like this should work:

```
git fetch origin
git rebase origin/master
# resolve conflicts
git push -f github HEAD:feature/calendar-export
```

Assuming that this repo is `origin` and your fork is `github`.

**Comment by ed-george** [comment]
Thanks - I was actually trying to do it through the new GH CLI, no idea what it's done.

Haven't had a chance to fix it up, but will look to do so this week

**Comment by ed-george** [comment]
@vmiklos - any issues let me know, apologies in the delay in getting this sorted :)

**Comment by vmiklos** [comment]
https://travis-ci.com/github/vmiklos/plees-tracker/builds/191208730#L1542 fails with:

```
e: /home/travis/build/vmiklos/plees-tracker/app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt: (338, 25): Type mismatch: inferred type is Array<String> but String! was expected
```

Reading your commit, looks like you lost the real meat during conflict resolution: the permission and string part is there, but none of the actual code to do exporting. Could you please fix that?

**Comment by ed-george** [comment]
Oh man, I've force-pushed over the work. Closing this, as I will need to look at it again once the shame has passed. I think I might go for a drink...

**Comment by vmiklos** [comment]
Just to state the obvious, all your initial work before the rebase I'd still here:

https://github.com/vmiklos/plees-tracker/commits/907c9e74e552dade8cd55645db4af42aaaef105f

Does that help? Although a drink is never a bad idea! :-)

**Comment by vmiklos** [comment]
Do you plan to open a PR for this or should I take this over? I would like to integrate this before it starts to bitrot. ;-)

**Comment by vmiklos** [comment]
I've opened #49 with a single commit that contains this work, but it's on top of latest master.

**Comment by ed-george** [comment]
Hi @vmiklos - apologies for the delay in getting back to you. If you have opened another issue with the code in, that's no problem :)

**Comment by vmiklos** [comment]
Yes, it's now merged. I hope to cut a new fdroid release over the weekend.

**Comment by ed-george** [comment]
Amazing - thanks for fixing my mess 👍

**Pull request closed without merging**
