### PR TITLE
auto-stop on phone movement and new service for auto-stop if phone is moved.    

### PR DESCRIPTION
**Pull request by ELY3M**
I did some changes.   just check this out if it is useful to you.

### CODE REVIEW

**Comment by vmiklos** [comment]
Hi!

Thanks for the PR. I haven't read all changes from start to end yet (and neither tried this out so far), so just some high-level, early feedback:

- The CI fails, does `./gradlew connectedAndroidTest` pass for you locally? It might be a one-off failure or some real problem.

- The added functionality should be optional, the readme states that plees tracker does nothing by default when you sleep and we should maintain that. Listening to sensor events unconditionally is not OK. If you make this a preference and it's off by default, then it is acceptable.

- Please read https://github.com/vmiklos/plees-tracker/pull/283/files yourself from start to end and ask yourself if you can explain each & every hunk you see there. Why did you change .idea/compiler.xml? Why did you add app/release/app-release.apk? And so on. :-)

- The git history does not include merge commits for this project. Please rebase your PR to get rid of the merge commit you would add.

All in all, looking forward to have this in, just it needs to be off by default and needs a bit of polish. Thanks!

**Comment by ELY3M** [comment]
I also added delete all sleep data function.    as for compiler.xml  I think it was android studio.   I use latest java and I was trying to see why it was whining about the version.

**Comment by vmiklos** [comment]
Can you reproduce your CI failure locally? If so, please investigate. Thanks!

**Comment by vmiklos** [comment]
This is the 3rd time CI fails on you and you add 2 independent features in one PR: delete all sleep + movement detection. Could you restrict this PR just to delete all sleep? And once that is in, let's deal with movement detection in a new PR. Thanks!

Or should I do this for you?

**Comment by ELY3M** [comment]
I am sorry,  I do not know what is CI. I am figuring it out right now.

**Comment by ELY3M** [comment]
I don't see any failures on CI locally here.  it said successful. I am on windows.

**Comment by ELY3M** [comment]
Please ignore this for now.   I am doing tests with CI in my repo and figuring out why your CI fails.    in my separate repo - the CI do not fail.

**Comment by vmiklos** [comment]
> I am sorry, I do not know what is CI.

Continuous Integration, i.e. the service that runs tests after your changes automatically.

> Please ignore this for now.

Fine, but could you please do that in an other branch, like "test"? CI would still build your commits in that branch in your fork, but this PR would not send out notifications for everyone watching after each & every commit.

> Or should I do this for you?

I'll limit this PR to just deleting sleeps so that your first contribution would be in. Then it's easier: your PRs get CI feedback without me manually approving the new commits one by one. :-)

Thanks.

**Comment by vmiklos** [comment]
Could you tick the checkbox to allow changes by maintainers? Then I can help to get this in. Thanks!

See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by vmiklos** [comment]
I've picked the "delete all sleep" feature from this PR to https://github.com/vmiklos/plees-tracker/pull/286.

Could you please rebase this on top of master? And unless you can meaningfully split your work into multiple commits, consider squashing all these "test" commits into a single one. Thanks.

**Comment by vmiklos** [comment]
Let's close this mess -- please open a new PR when you have clean branch history with one or more correctly documented commits and no merge conflicts. Thanks!!

**Pull request closed without merging**
