### PR TITLE
Update tools and libraries to latest recommended version

### PR DESCRIPTION
**Pull request by ed-george**

### CODE REVIEW

**Comment by vmiklos** [comment]
If you update espresso, please also port the code away from the now deprecated API. The two has to be done in a single commit. Perhaps also break out the other upgrade to a separate PR?

**Comment by ed-george** [comment]
Oops apologies for that @vmiklos - this is now updated

**Comment by vmiklos** [comment]
Looks good to me now, thanks.

**Comment by vmiklos** [comment]
Are you interested in a next PR for PleesTracker? E.g. https://github.com/vmiklos/plees-tracker/issues/32 may be reasonably straightforward, but less boring and more fun than this version update. :-)

**Comment by ed-george** [comment]
@vmiklos I am actually looking at #29 - will make a PR when I get a chance but so far so good 👍

**Comment by vmiklos** [comment]
Ah nice, then ignore my hint.

**Pull request merged**
