### PR TITLE
Add settings page to select theme, fix light mode

### PR DESCRIPTION
**Pull request by martiandolphin**

### CODE REVIEW

**Comment by vmiklos** [comment]
Can you please rebase to resolve conflicts? :-) Thanks.

**Comment by martiandolphin** [comment]
I think I already did. Github says there aren't conflicts anymore

**Comment by vmiklos** [comment]
Ah, I see the confusion. This repo uses rebases (not merges), so when I tried to "rebase + push" your commits, I got conflicts. I just force-pushed a squashed merge commit to this PR so I can accept this without polluting the repo history with merge commits.

**Comment by vmiklos** [comment]
Looks good to me now, thanks! :-)

**Pull request merged**
